config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "main#index"
  get "/main", to: "main#index"

  resource :session, only:[:new, :create, :destroy]

  resources :users, only: [:new, :create]



resources :games do

  resources :topics do

      resources :comments

  end

end


resources :topics do

  resources :comments

end

resources :rentals 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :topic
    # Rails generator automatically adds a "belongs_to" statement in the model
    #  This will help us later work with associated records.
    belongs_to :user
    belongs_to :game
    

end

app/models/game.rb
class Game < ApplicationRecord

    belongs_to :user
    has_many :topics, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :rentals, dependent: :destroy
  


end

app/models/message.rb
class Message < ApplicationRecord

    belongs_to :user
    belongs_to :rental

end

app/models/rental.rb
class Rental < ApplicationRecord

    belongs_to :user
    belongs_to :game

    
end

app/models/topic.rb
class Topic < ApplicationRecord

    belongs_to :user
    belongs_to :game
    has_many :comments, dependent: :destroy
  

    validates :title, presence: true
    # validates :reserve_price, presence: true



    validates :title, presence: { message: "Title must be provided"} , uniqueness: {scope: :body}, length: { minimum: 2, maximum: 200, too_short: "Title must be 2 characters minimum" }




    validates :body, presence: { message: "Body must be provided" }

    validates :view_count, numericality: { greater_or_equal_to: 0 }



    def set_defaults
        #self.view_count = 0 if self.view_count.nil?
        self.view_count ||= 0
    end

    def capitalize_title
        self.title.capitalize!
    end
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    has_many :topics, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :games
    has_many :rentals, dependent: :destroy
  
    # VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true
  
    def full_name
      self.first_name + " " + self.last_name
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # ===============CALLBACKS====================
  before_action :find_game, only: [:edit, :update, :show, :destroy]

# ===============CREATE========================
def new
  
    @game = Game.new
  end




# =====READ============
def index

    @games = Game.order(created_at: :desc)

end


def show
    @topics = @game.topics.order(created_at: :desc)
    @rentals = @game.rentals.order(created_at: :desc)
    
    @topic = Topic.new
    @comment = Comment.new
  
    
end


private

def find_game
    @game = Game.find params[:id]
end

#   def question_params
#     params.require(:game).permit(:title, :body, :tag_names)
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index
     
    end



end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

 # ===============CALLBACKS====================
 before_action :find_rental, only: [:edit, :update, :show, :destroy]


# ===============CREATE========================
def new
  
    @rental = Rental.new
end


# =====READ============
def index
    
    @rentals = Rental.order(created_at: :desc)
    
end

def show
end



private

def find_rental
    @rental = Rental.find params[:id]
end



end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
 # ===============CALLBACKS====================
 before_action :find_topic, only: [:edit, :update, :show, :destroy]


    

# ===============CREATE========================
def new
  
    @topic = Topic.new
end


# =====READ============
def index
    @comment = Comment.new
    @topics = Topic.order(created_at: :desc)

end


def show
    @comments = @topic.comments.order(created_at: :desc)
   
    @comment = Comment.new
  
    
end


private

def find_topic
    @topic = Topic.find params[:id]
end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/games/index.html.erb
<div class="container">
<h2>Games Catalog Page</h2>
<h4>A place to find all the games you want to play...</h4>
<br>

<%= image_tag("bar6.png")  %>
<br>
<br>
<hr>

</div>
<div class="container">
  <% @games.each do |game| %>
    <ul>
      <div>
      <div>
        
        <h4><%= link_to game.title, game %></h4>
     
        <br>
      </div>
    
       
          
      <%= image_tag(game.image_url, class: "index-image")%>
      <br>
      <br>
      <h5>Game Review Score</h5>
      <h5>Most played ranking</h5>
      
   
        </ul>
        
     
      <hr>
      <br>

  <% end %>
  <%= image_tag("bar.png")  %>
</div>

app/views/games/show.html.erb
<div class="container">
  
<h3>Game Show page</h3>
<h5>Find info, available rentals and topics about this game...</h5>
<br>
<%= image_tag("bar1.png")  %>

<br>
<br>

<div class="container">
<h3><%= @game.title %></h3>
<br>
<%= image_tag(@game.image_url, class: "show-image")%>
<br>
<br>
<div class="container">
<p><%= @game.description %></p>
</div>
<h5>platform</h5>

<h5>Game Reviews</h5>

<h5>User Reviews</h5>
<h5>other related game info</h5>
<br>
<hr>

<h4>Suggested rental price:</h4>
<h4>$<%= @game.suggested_rental_price %> per week </h4>
<br>

</div>
<%= image_tag("bar1.png")  %>
<br>
<br>
<h4>Available rentals:</h4>

 <% @rentals.each do |rental| %>
 
 <ol>
  <h5><%= link_to rental.description, rental %></h5>
  <h5>Game owner: <%= rental.user.first_name %></h5>
  <ul>
  <h5><%= rental.rental_time %> Weeks for $ <%= rental.rental_price %></h5>
  </ul>
  </ol>
  <hr>
 <% end %>
 <button>To post yours here</button>
 <br>

<br>
 <%= image_tag("bar.png")  %>
 <br>
<br>
 <h4>Forum Topics about this game:</h4>
 
 <button>Post new topic about this game</button>
<hr>
<ul>
  <% @topics.each do |topic| %>
    <li>
    <h3></h3>
     <%= topic.title %>
     <br>
      <%= topic.body %>
    </li>
    <button>Reply to this topic</button>
    <br>
    <br>
  <ul>
    <% topic.comments.order(created_at: :desc).each do |comment| %>
    <li>
      <%= comment.body %>
      <br>
    <% end %>
    
    </li>
  </ul>
  <hr>
    <br>
   
  <% end %>
  
</ul>

<%= image_tag("bar.png")  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PsPlayshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav>

<div class="container">
  <%= image_tag("bar.png")  %>
 <a href="/main"> <%= image_tag("weblogo.png", class: "logo-img")  %> </a>



   <span class = "title"><%= link_to "△Games", games_path %></span>
    
    
   <span class = "title"><%= link_to "▢Rentals", rentals_path %></span>
    
        
   <span class = "title"><%= link_to "◯Forum", topics_path %></span>

   <span class = "title"><%= link_to "✕SignIn/SignOn", root_path %></span>
   <%= image_tag("bar1.png")  %>
  </div>
    <br>
    </nav>









  
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<div class="container">
<h2>Main Page</h1>
    <br>
<h4>A place for the PlayStation gamers to share your games,</h4>
<h4>gaming experience,</h4>
<h4>and much more...</h4>
<br>
</div>
<div class="container">
<%= image_tag("bar1.png")  %>
<br>
<br>
<h5>Sponsor Ads/Game news/other info...</h5>
<%= image_tag("psdeals.png", class: "ads-img")  %>
<hr>
<%= image_tag("lego.png", class: "ads-img")  %>
<hr>
<%= image_tag("bestbuy.png", class: "ads-img")  %>
<%= image_tag("bar.png")  %>
</div>

app/views/rentals/index.html.erb
<div class="container">



<h2>Game Rentals Page</h2>
<h4>All available game rentals here...</h4>
<br>
<%= image_tag("bar6.png")  %>
<br>
<br>
<hr>

<% @rentals.each do |rental| %>

  <div>
    <br>
    <h3><%= link_to rental.title, rental %></h3>
    <br>
    <%= image_tag(rental.image_url, class: "index-image")%>
    <br>
    <br>
    <h5>Game owner: <%= rental.user.first_name %></h5>
    <h5>Game owner address: Vancouver Area</h5>
    <h5>Rental Price: $<%= rental.rental_price %></h5>
      
    <h5>Rental period: <%= rental.rental_time %> weeks</h5>
    
    
    <hr>
  </div>
<% end %>

</div>

app/views/rentals/show.html.erb
<div class="container">
 
    <h2>Game Rental Show page</h2>
    <h5>To rent this game and contact with game owner..</h5>
    <br>
    <%= image_tag("bar1.png")  %>
    <br>
    <br>
    <ul>
    <h2><%= @rental.title %></h2>
    <br>
    <%= image_tag(@rental.image_url, class: "show-image")%>
    <br>
    <br>
    <h4>Game owner: <%= @rental.user.first_name %></h4>
    <br>
    <h5>Game owner address: Vancouver Area</h5>
    <br>
    <h5>Game owner discription:</h5>
    <p><%= @rental.description %></p>

    <br>
    <h4>Rental price:</h4>
    <h5>$ <%= @rental.rental_price %>  </h5>

    <h4>Rental time:</h4>
    <h5>$ <%= @rental.rental_time %> weeks </h5>
    <br>


    <button>Leave a message</button> 

 

</div>
<div class="container">
<%= image_tag("bar.png")  %>
</div>

app/views/topics/index.html.erb
<div class="container">


<h2>Forum Page</h2>
<h4>A plae to share your gaming experience...</h4>

<br>
<%= image_tag("bar1.png")  %>
<br>
<br>
<button>Start a new topic</button> 
<br>
<br>
<div class="container">
<% @topics.each do |topic| %>


  <div>
    <h4><%= link_to topic.title, topic %></h4>
    
    <%= topic.body %>
    <button>Reply to this topic</button> 
    <br>
    <br>
  </div>

<% topic.comments.order(created_at: :desc).each do |comment| %>

<ul>
<li>
<%= comment.body %>
</li>
</ul>
  <% end %>
  <br>
  <hr>
  <br>

<% end %>
</ul>
</div>
</div>


 

app/views/topics/show.html.erb
<h1>Topic Show page</h1>

<h3>Game Topic: <%= @topic.title %></h3>
<ul>
<h3><%= @topic.body %></h3>
</ul>

<% @comments.each do |comment| %>
  <ul>
  <ul>
    <h4>Comment:</h4>
      <%= comment.body %>
   </ul>
   </ul>
  <% end %>